[package]
name = "sphere-sys"
version = "0.1.0"
authors = ["Bjoern Quentin <bjoern.quentin@grandcentrix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.65"

[build-dependencies]
bindgen = "0.52.0"